name: hospital_managment_system
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.1.1
  dropdown_search: ^5.0.6
  image_picker: ^1.0.0
  flutter_otp_text_field: ^1.1.1
  carousel_slider: ^4.2.1
  rounded_loading_button: ^2.1.0
  loading_animation_widget: ^1.2.0+4
  http: ^1.1.0
  cached_network_image: ^3.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"
  background_color: Color(0xff09488b)


flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/banner/
  fonts:
    - family: "PoppinsBlack"
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: "PoppinsBlackItalic"
      fonts:
        - asset: assets/fonts/Poppins-BlackItalic.ttf
    - family: "PoppinsBold"
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: "PoppinsBoldItalic"
      fonts:
        - asset: assets/fonts/Poppins-BoldItalic.ttf
    - family: "PoppinsExtraBold"
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: "PoppinsExtraBoldItalic"
      fonts:
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
    - family: "PoppinsExtraLight"
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: "PoppinsExtraLightItalic"
      fonts:
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
    - family: "PoppinsItalic"
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
    - family: "PoppinsLight"
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: "PoppinsLightItalic"
      fonts:
        - asset: assets/fonts/Poppins-LightItalic.ttf
    - family: "PoppinsMedium"
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: "PoppinsMediumItalic"
      fonts:
        - asset: assets/fonts/Poppins-MediumItalic.ttf
    - family: "PoppinsRegular"
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: "PoppinsSemiBold"
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: "PoppinsSemiBoldItalic"
      fonts:
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
    - family: "PoppinsThin"
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: "PoppinsThinItalic"
      fonts:
        - asset: assets/fonts/Poppins-ThinItalic.ttf








